INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project One", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Two", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Three", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Four", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Five", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Six", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Seven", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Eight", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Nine", "Fundraiser", 10000, "3/31/2019", "3/31/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Project Ten", "Fundraiser", 10000, "3/31/2019", "3/31/2020");

INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");
INSERT INTO users (name) VALUES ("Jane");

INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 1,1);